# Default values for alertmanager-sns-forwarder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alertmanager-sns-forwarder
  tag: 0.1
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9087

podAnnotations:
  iam.amazonaws.com/role: "arn:aws:iam::773355297247:role/eks-sns-forwarder"
  


servicemonitor:
  enabled: true

sns:
  forwarder:
    debug: true
    arn:
      prefix: "arn:aws:sns:eu-central-1:773355297247:eks-alertmanager-sns"

resources: 
  limits:
    memory: 1Gi
    cpu: 0.5
  requests:
    cpu: 0.2
    memory: 0.5Gi

nodeSelector: {}

tolerations: []

affinity: {}