apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertmanager-sns-forwarder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager-sns-forwarder.name" . }}
    helm.sh/chart: {{ include "alertmanager-sns-forwarder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alertmanager-sns-forwarder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alertmanager-sns-forwarder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        iam.amazonaws.com/role: sns-forwarder-role
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9087
              name: webhook-port
          livenessProbe:
            httpGet:
              path: /health
              port: webhook-port
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: webhook-port
            initialDelaySeconds: 30
            timeoutSeconds: 10
          env:
            - name: AWS_REGION
              value: "eu-central-1"
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
